// variable de inico de la aplicacion
var vigilante = true;
var categoria = 'aluraInst';
var letraspulsadas = '';
var fondoHorcas = [
	'./images/Horca001.png',
	'./images/Horca002.png',
	'./images/Horca003.png',
	'./images/Horca004.png',
	'./images/Horca005.png',
	'./images/Horca006.png',
	'./images/Horca007.png',
	'./images/Horca008.png',
	'./images/Horca009.png',
	'./images/Horca010.png',
	'./images/Horca011.png',
];

var palabras = {
	aluraInst: [
		'JEANMARIE',
		'GENESYS',
		'CHRISTIAN',
		'BRUNO',
		'ANA MARIA',
		'PRISCILA',
		'ELISABETH',
		'DANIEL',
		'ELLEN',
		'GABRIELA',
		'MAURICIO',
		'RAQUEL',
		'JIMENA',
		'LEONARDO',
		'MIGUEL',
		'HARLAND',
		'TATIANI',
		'WILLIAMS',
	],
	deportes: [
		'TENIS',
		'FUTBOL',
		'BALONCESTO',
		'BEISBOL',
		'VOLEIBOL',
		'AUTOMOVILISMO',
		'ATLETISMO',
		'NATACION',
		'CANOTAJE',
		'WINDSURF',
		'BOXEO',
		'CICLISMO',
		'BADMINTON',
		'BALONMANO',
		'BOWLING',
		'ESGRIMA',
		'HOCKEY',
		'RUGBY',
		'GIMNASIA',
	],
	paises: [
		'VENEZUELA',
		'COLOMBIA',
		'PERU',
		'BRASIL',
		'CHILE',
		'BOLIVIA',
		'ARGENTINA',
		'URUGUAY',
		'PARAGUAY',
		'ECUADOR',
		'SURINAN',
		'CANADA',
		'BELICE',
		'BARBADOS',
		'BAHAMAS',
		'ANTIGUA Y BARBUDA',
		'COSTA RICA',
		'CUBA',
		'DOMINICA',
		'EL SALVADOR',
		'ESTADOS UNIDOS',
		'GRANADA',
		'PANAMA',
		'HONDURAS',
		'NICARAGUA',
		'MEXICO',
		'GUATEMALA',
		'GUYANA',
		'HAITI',
		'JAMAICA',
		'REPUBLICA DOMINICANA',
		'SAN CRISTOBAL Y NIEVES',
		'SAN VICENTE Y LAS GRANADINAS',
		'SANTA LUCIA',
		'TRINIDAD Y TOBAGO',
	],

	peliculas: [
		'STAR WARS',
		'EL PADRINO',
		'AVATAR',
		'TITANIC',
		'IRON MAN',
		'SCREAM',
		'LA CIUDAD PERDIDA',
		'LOS CAZAFANTASMAS',
		'TOP GUN',
		'EL PADRINO',
		'MAD MAX',
		'TIBURON',
		'EL EXORCISTA',
		'RAMBO',
		'TERMINATOR',
		'TORO SALVAJE',
		'ALIEN',
		'BLADE RUNNER',
		'CIUDADANO KANE',
	],

	lenguajes: [
		'JAVASCRIPT',
		'HTML',
		'CSS',
		'PYTHON',
		'JAVA',
		'C',
		'PASCAL',
		'COBOL',
		'FORTRAN',
		'RUBY',
		'SCALA',
		'LUA',
		'PHP',
		'VISUAL BASIC',
		'LIST',
		'TYPESCRIPT',
		'SWIFT',
		'PERL',
		'KOTLIN',
		'RUST',
	],
};
